### PR TITLE
bump dynamiclistener to v0.3.5

### PR DESCRIPTION
**Pull request by chrisho**
v0.3.5 to fix cert refresh, improve performance.

Before bumping dynamiclistener v0.3.5
```bash
➜  ~ k top pod harvester-network-webhook-7bbdc8f4dc-jcg4f
NAME                                         CPU(cores)   MEMORY(bytes)
harvester-network-webhook-7bbdc8f4dc-jcg4f   201m         167Mi
➜  ~ k top pod harvester-network-webhook-7bbdc8f4dc-jcg4f
NAME                                         CPU(cores)   MEMORY(bytes)
harvester-network-webhook-7bbdc8f4dc-jcg4f   201m         167Mi
```

After bumping dynamiclistener v0.3.5
```bash
k top pod harvester-network-webhook-64b48b496c-hgchv
NAME                                         CPU(cores)   MEMORY(bytes)
harvester-network-webhook-64b48b496c-hgchv   74m          170Mi
➜  ~ k top pod harvester-network-webhook-64b48b496c-hgchv
NAME                                         CPU(cores)   MEMORY(bytes)
harvester-network-webhook-64b48b496c-hgchv   74m          170Mi
```

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, thanks. can u also help to check if this will also apply to the harvester webhook, thanks.

**Comment by chrisho** [comment]
> LGTM, thanks. can u also help to check if this will also apply to the harvester webhook, thanks.

I tried, but there are some conflicts for other packages that can not be solved like harvester/webhook, needs to discuss the solution with the rancher team

**Comment by guangbochen** [comment]
sure, this is not a required change for now and let's track the `harvester/harvester` repo in future versions, thanks.

**Review by yaocw2020 — APPROVED** [review]
LGTM, thanks

**Comment by chrisho** [comment]
https://github.com/harvester/harvester/issues/3008

**Pull request merged**
