### PR TITLE
fix: restrict the tls cipher

### PR DESCRIPTION
**Pull request by Yu-Jack**
Related Issue: https://github.com/harvester/security/issues/42

### CODE REVIEW

**Comment by ibrokethecloud** [comment]
in my original PR I had also specified `MinVersion` for TLS https://github.com/harvester/harvester/pull/4730/files#diff-6404509afd56daa425812290afd70394d934e45a776dcdb36087716a660c113aR167 do we want to keep that as well?

**Comment by Yu-Jack** [comment]
> in my original PR I had also specified `MinVersion` for TLS https://github.com/harvester/harvester/pull/4730/files#diff-6404509afd56daa425812290afd70394d934e45a776dcdb36087716a660c113aR167 do we want to keep that as well?

Sounds good for me, let me add it.

**Review by bk201 — APPROVED** [review]
LGTM!

**Review by starbops — APPROVED** [review]
LGTM, thanks!

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Pull request merged**
